-- fusionreactionstorage
-- fusionreactionhoverfac
-- fusionreactionmaker
-- fusionreactionbasic
-- fusionreactionnuclear
-- fusionreactiongeo
-- fusionreactionmex
-- fusionreaction
-- fusionreactionmakernew
-- fusionreactionstoragenew
-- fusionreactionburrow

return {
  ["fusionreactionstorage"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
    underwater_electricarcs1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionhoverfac"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionmaker"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
    underwater_electricarcs1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionbasic"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 2,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
    underwater_electricarcs1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionnuclear"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 2,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  }, 

  ["fusionreactiongeo"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water         	 = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 2,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionmex"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.2 0.5 0.9 0.01  0.1 0.5 0.7 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 2,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreaction"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.2 0.5 0.9 0.01  0.1 0.5 0.7 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
    underwater_electricarcs1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionstoragenew"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionstoragenew-blue"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

  ["fusionreactionburrow"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0.5 0.01  0.8 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 4,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
    underwater_electricarcs1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      underwater         = 1,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0.5 0.01  0.8 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 4,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
----------------------------------------------------------
-- Begin fusionreactionnuclear-small
----------------------------------------------------------
  
  ["fusionreactionnuclear-small-1color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-small-2color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },

  ["fusionreactionnuclear-small-3color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-purple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-small-4color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-purple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors3 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r120]],
        explosiongenerator = [[custom:fusionreactionnuclear-small-green]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-small-orange"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 0.9,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclear-small-blue"] = {
	electricarcs1 = {
	  air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
	  ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 0.9,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclear-small-purple"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water         	 = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.6 0 0.6 0.01  0.3 0 0.6 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 0.9,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclear-small-green"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water         	 = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0.5 0 0.01  0 0.8 0.2 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 0.9,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
----------------------------------------------------------
-- End fusionreactionnuclear-small
---------------------------------------------------------- 

----------------------------------------------------------
-- Begin fusionreactionnuclear
---------------------------------------------------------- 
  
  ["fusionreactionnuclear-1color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclearorange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-2color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclearorange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclearblue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },

  ["fusionreactionnuclear-3color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclearorange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclearblue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclearpurple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-4color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r500]],
        explosiongenerator = [[custom:fusionreactionnuclearorange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclearblue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclearpurple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors3 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r120]],
        explosiongenerator = [[custom:fusionreactionnucleargreen]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclearorange"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclearblue"] = {
	electricarcs1 = {
	  air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
	  ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclearpurple"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water         	 = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.6 0 0.6 0.01  0.3 0 0.6 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnucleargreen"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water         	 = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0.5 0 0.01  0 0.8 0.2 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
----------------------------------------------------------
-- End fusionreactionnuclear
---------------------------------------------------------- 
  
----------------------------------------------------------
-- Begin fusionreactionnuclear-huge
---------------------------------------------------------- 

  ["fusionreactionnuclear-huge-1color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r30]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },

  ["fusionreactionnuclear-huge-2color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r30]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },

  ["fusionreactionnuclear-huge-3color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r30]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-purple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-huge-4color"] = {
	othercolors = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        --delay              = [[10 r30]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-orange]],
        --pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r60]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-blue]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r90]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-purple]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
	othercolors3 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 2,
      ground             = true,
      water              = true, 
	  underwater         = true,
      properties = {
        delay              = [[10 r120]],
        explosiongenerator = [[custom:fusionreactionnuclear-huge-green]],
        pos                = [[5 r5, 1, 5 r5]],
      },
    },
  },
  
  ["fusionreactionnuclear-huge-orange"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionnuclear-huge-blue"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0 0.5 0.01  0 0.5 0.8 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },  
  
  ["fusionreactionnuclear-huge-purple"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.6 0 0.6 0.01  0.3 0 0.6 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  }, 
  
  ["fusionreactionnuclear-huge-green"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0.5 0 0.01  0 0.8 0.2 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 15,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.02, 0]],
        numparticles       = 1,
        particlelife       = 45,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  }, 
  
----------------------------------------------------------
-- End fusionreactionnuclear-huge
---------------------------------------------------------- 

----------------------------------------------------------
-- Begin fusionreactionmaker
---------------------------------------------------------- 

  ["fusionreactionmaker-orange"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0 0 0.01  0.8 0.5 0 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionmaker-blue"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.2 0.5 0.9 0.01  0.1 0.5 0.7 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionmaker-purple"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0.6 0 0.6 0.01  0.3 0 0.6 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },
  
  ["fusionreactionmaker-green"] = {
    electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  water              = true,
      underwater         = true,
      properties = {
        airdrag            = 1,
        --alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04   0 0.5 0 0.01  0 0.8 0.2 0.01	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 70,
        particlelifespread = 1,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.2,
        particlespeedspread = 1,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.6,
        sizemod            = 1,
        texture            = [[plasmaball]],
        useairlos          = false,
      },
    },
  },

----------------------------------------------------------
-- end fusionreactionmaker
---------------------------------------------------------- 

}

