return {
--hover
    ["emissiletanktrail-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 15,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 31,
        sidetexture        = [[flashside2-red]],
        size               = 5,
        sizegrowth         = 0,
        ttl                = 40,
      },
    },
  },
  
--hbot
    ["ehbotrocko-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 15,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 31,
        sidetexture        = [[flashside2-purple]],
        size               = 5,
        sizegrowth         = 0,
        ttl                = 40,
      },
    },
  },

--amphibs
    ["amphibrocktrail-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 15,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 30,
        sidetexture        = [[flashside2-orange]],
        size               = 5,
        sizegrowth         = 0,
        ttl                = 30,
      },
    },
  },


--aircraft
    ["gunshiptrail-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 32,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 31,
        sidetexture        = [[flashside2]],
        size               = 5,
        sizegrowth         = 0,
        ttl                = 20,
      },
    },
  },
  
  
  ["bombertrail-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 32,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 31,
        sidetexture        = [[flashside2-red]],
        size               = 10,
        sizegrowth         = 0,
        ttl                = 20,
      },
    },
  },
    ["emptrail-optimized"] = {
    engine = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.73 0.4 0.01   1 0.64 0.25 0.01   1.0 0.4 0.12 0.01   0.5 0.22 0.03 0.01   0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 60,
        sidetexture        = [[sparkexplo]],
        size               = 5,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    trail = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.70 0.70 0.70 0.025   0.05 0.05 0.05 0.025   0 0 0 0.01	0 0 0 0.0]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[none]],
        length             = 60,
        sidetexture        = [[flashside2-blue]],
        size               = 15,
        sizegrowth         = 0,
        ttl                = 20,
      },
    },
  },
}