unitDef                    = {
	activateWhenBuilt             = true,
	buildAngle                    = 16384,
	buildCostEnergy               = 0,
	buildCostMetal                = buildCostMetal,
	builder                       = false,
	buildTime                     = 5,
	category                      = "BUILDING NOTAIR",
	description                   = [[Radar Dome/Sensor Tower]],
	energyMake                    = 0,
	energyStorage                 = 0,
	energyUse                     = 0,
	explodeAs                     = "largeBuildingExplosionGenericWhite",
	footprintX                    = 6,
	footprintZ                    = 6,
	floater			              = true,
	iconType                      = "radar",
	idleAutoHeal                  = .5,
	idleTime                      = 2200,
	isTargetingUpgrade            = false,
	maxDamage                     = 250,
	maxSlope                      = 75,
	maxWaterDepth                 = 999999,
	metalStorage                  = 0,
	name                          = humanName,
	objectName                    = objectName,
	script			              = "eradar3.cob",
	onoffable                     = false,
	radarDistance                 = radarDistance,
	radarEmitHeight				  = radarEmitHeight,
	repairable		              = false,
	selfDestructAs                = "largeBuildingExplosionGenericWhite",
	side                          = "CORE",
	sightDistance                 = sightDistance,
	smoothAnim                    = true,
	sonarDistance                 = sonarDistance,
	seismicDistance               = seismicDistance,
	unitname                      = "eradar2",
	workerTime                    = 0,
	yardMap                       = "oooooo oooooo oooooo oooooo oooooo oooooo",

	sfxtypes                      = {
		pieceExplosionGenerators  = {
			"deathceg3",
			"deathceg4",
		},
		
		explosiongenerators       = {
			"custom:blacksmoke",
		},
	},

	sounds                        = {
		underattack               = "other/unitsunderattack1",
		select                    = {
			"other/gdradar",
		},
	},
	customParams                  = {
		RequireTech				 = techrequired,
		unittype				  = "building",
		needed_cover              = 2,
		death_sounds              = "generic",
		armortype                 = armortype,
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                 = "unittextures/lego2skin_explorerbucket.dds",
		factionname	              = "ateran",
		corpse                   = "energycore",
		helptext                  = [[]],
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "factorygroundplate.dds",
	BuildingGroundDecalSizeX      = 8,
	BuildingGroundDecalSizeY      = 8,
	BuildingGroundDecalDecaySpeed = 0.9,
}
