local objectname= "metal = 0,
--metal" 
local featureDef	=	{
	name			= "metal = 0,
--metal",
	world				="allworld",
	description				="metal = 0,
--metal Patch",
	category				="Resource",
	object				="metal = 0,
--metal.s3o",
	footprintx				=4,
	footprintz				=4,
	height				=5,
	blocking				=false,
	hitdensity				=0,
	energy = 10,
-- energy				=0,
	metal = 0,
--metal				=0,
	damage				=9999999999,
	flammable				=false,
	reclaimable				=false,
	autoreclaimable				=false,
	indestructible				=true,
	customparams = { 
		randomrotate		= "true", 
	}, 
}
return lowerkeys({[objectname] = featureDef}) 
