unitDef                    = {
	--acceleration                 = 0.5,
	airStrafe                    = false,
	airHoverFactor				 = 0,
	--brakeRate                    = 1,
	buildCostEnergy              = 0,
	buildCostMetal               = 60,
	builder                      = false,
	buildTime                    = 2.5,
	buildpic					 = "ebomber.png",
	canAttack                    = true,
	canFly                       = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = true,
	category                     = "AIRARMORED VTOL",
	collide                      = true,
	cruiseAlt                    = 400,
	description                  = [[Bomber]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "largeExplosionGeneric",
	footprintX                   = 4,
	footprintZ                   = 4,
	floater                      = true,
	hoverAttack                  = false,
	iconType                     = "air_bomb",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	loopbackattack               = true,
	maxacc						 = 1,
	
	maxAileron					 = 0.01,
	maxElevator					 = 0.01,
	maxRudder					 = 0.01,
	maxBank					 	 = 0.01,
	
	maxDamage                    = 670,
	maxSlope                     = 90,
	maxVelocity                  = 13,
	verticalSpeed		         = 15,
	maxWaterDepth                = 0,
	metalStorage                 = 0,
	name                         = humanName,
	objectName                   = objectName,
	script			             = script,
	repairable		             = false,
	selfDestructAs               = "largeExplosionGeneric",
	side                         = "CORE",
	sightDistance                = 400,
	smoothAnim                   = true,
	stealth                      = false,
	transportbyenemy             = false;
	turnRate                     = 5000,
	unitname                     = unitName,
	upright						 = true,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:jethtrail",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "bomb",
			onlyTargetCategory	 = "BUILDING",
			noChaseCategory      = "VTOL LIGHT ARMORED",
		},
	},
	customParams                 = {
		isupgraded				 = isUpgraded,
		unittype				 = "mobile",
		--    needed_cover       = 2,
		death_sounds             = "generic",
		nofriendlyfire           = "1",
		RequireTech              = tech,
		armortype                = armortype,
		nofriendlyfire	         = "1",
		supply_cost              = supply,
		normaltex                = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "ateran",
		corpse                   = "energycore",
		retreatRangeDAI			 = 0,
	},
}

weaponDefs                 = {

	missile                      = {
		AreaOfEffect             = 300,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		cegTag                   = "bombertrail-optimized",
		explosionGenerator       = "custom:genericshellexplosion-large-red",
		energypershot            = 0,
		edgeEffectiveness        = 0.1,
		fireStarter              = 70,
		
		id                       = 136,
		impulseBoost             = 0,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		
		metalpershot             = 0,
		model                    = "missile.s3o",
		name                     = "Rockets",
		range                    = 800,
		reloadtime               = 6,
		weaponType		         = "MissileLauncher",		
		
		smokeTrail               = false,
		soundHit                 = "other/18402_inferno_xplo.wav",
		soundHitWet				 = "explosions/subhitbomb.wav",
		soundHitVolume	         = 10,
		soundStart               = "weapons/bomberlaunch.wav",
		soundStartVolume         = 10,
		
		startVelocity            = 200,
		tolerance                = 8000,
		turnRate                 = 15000,
		tracks                   = false,
		turret			         = false,
		weaponAcceleration       = 50,
		waterweapon				 = true,
		flightTime               = 10,
		weaponVelocity           = 800,
		customparams             = {
			isupgraded			 = isUpgraded,
			damagetype		     = "antibuilding",  
			nofriendlyfire	     = 1,
		},
		damage                   = {
			default              = 500,
		},
	},
	
	bomb  	             = {
		AreaOfEffect             = 150,
		avoidFeature             = false,
		avoidFriendly            = false,
		collideFeature           = false,
		collideFriendly          = false,
		cylinderTargeting		 = 0,
		burst					 = 10,
		burstrate				 = 0.1,
		cegTag                   = "genericshellexplosion-large-sparks-burn",
		energypershot            = 0,
		explosionGenerator       = "custom:genericshellexplosion-medium-red",
		fallOffRate              = 1,
		fireStarter              = 50,
		impulseFactor            = 0,
		minintensity             = "1",
		name                     = "Cluster Bomb",
		range                    = 1000,
		reloadtime               = 6,
		WeaponType               = "Cannon",
		rgbColor                 = "1 0.5 0",
		rgbColor2                = "1 1 1",
		soundTrigger             = true,
		soundstart               = "weapons/bombdrop.wav",
		soundHit                 = "other/18402_inferno_xplo.wav",
		soundHitWet				 = "explosions/subhitbomb.wav",
		sprayangle				 = 5000,
		size					 = 4,
		--texture1                 = "shot",
		--texture2                 = "empty",
		thickness                = 15,
		tolerance                = 7500,
		turret                   = false,
		weaponVelocity           = 150,
		customparams             = {
			damagetype		     = "antibuilding",
			isupgraded           = isUpgraded,
			nofriendlyfire	     = 1,
		}, 
		damage                   = {
			default              = 100,
		},
	},  
}
