unitDef                    = {
	acceleration                 = 0.5,
	airStrafe                    = true,
	airHoverFactor				 = 0,
	bankscale                    = "1",
	brakeRate                    = 0.7,
	buildCostEnergy              = 0,
	buildCostMetal               = 80,
	buildTime                    = 2.5,
	buildpic					 = "efighter.png",
	canAttack                    = true,
	canFly                       = true,
	canGuard                     = true,
	canLoopbackAttack            = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	category                     = "LIGHT VTOL",
	collide                      = true,
	cruiseAlt                    = 75,
	description                  = [[Anti-Light Drone • Uses +]] .. supply .. [[ Supply]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "mediumExplosionGenericWhite",
	footprintX                   = 5,
	footprintZ                   = 5,
	hoverAttack                  = true,
	floater                      = true,
	iconType                     = "air_lit",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	maxAcc                       = 0.25,
	maxBank			             = 5,
	maxDamage                    = 406,
	maxSlope                     = 90,
	maxVelocity                  = 7.5,
	--verticalSpeed		         = 15,
	maxWaterDepth                = 255,
	metalStorage                 = 0,
	moverate1                    = "8",
	name                         = humanName,
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = "mediumExplosionGenericWhite",
	side                         = "ARM",
	sightDistance                = 500,
	smoothAnim                   = true,
	sonarDistance                = 0,
	transportbyenemy             = false;
	turnRate                     = 5000,
	unitname                     = unitName,
	upright						 = true,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:gdhcannon",
			"custom:jethtrail",
			"custom:blacksmoke",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "aircannon",
			badTargetCategory    = "ARMORED BUILDING VTOL",
		},
	},
	customParams                 = {
		unittype				 = "mobile",
		--    needed_cover       = 2,
		isupgraded               = isUpgraded,
		death_sounds             = "generic",
		RequireTech              = tech,
		armortype                = armortype,
		nofriendlyfire	         = "1",
		supply_cost              = supply,
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "outer_colonies",
		corpse                   = "energycore",
	},
}

weaponDefs                 = {
	aircannon   	             = {
		AreaOfEffect             = 25,
		avoidFeature             = false,
		avoidFriendly            = false,
		collideFeature           = false,
		collideFriendly          = false,
		coreThickness            = 0.5,
		beamTime                 = 0.1,
		beamTTL					 = 10,
		beamDecay				 = 1,
		burnblow		         = true,
		largeBeamLaser           = true,
		laserflaresize 	         = 7,
		minIntensity			 = 1,
		--cegTag                   = "railgun",
		duration                 = 0.6,
		edgeeffectiveness		 = 1,
		energypershot            = 0,
		explosionGenerator       = "custom:genericshellexplosion-small-sparks-burn",
		fallOffRate              = 0.1,
		fireStarter              = 50,
		impulseFactor            = 0,
		fallOffRate				 = 0,
		interceptedByShieldType  = 4,
		minintensity             = 1,
		name                     = unitName .. "Weapon",
		range                    = 200,
		reloadtime               = 0.5,
		WeaponType               = "BeamLaser",
		waterweapon				 = true,
		rgbColor                 = "0 1 1",
		rgbColor2                = "1 1 1",
		soundTrigger             = true,
		soundstart               = "weapons/efighterlaser.wav",
		--soundHit                 = "explosions/artyhit.wav",
		texture1                  = "lightning",
		texture2                  = "laserend",
		thickness                = 7,
		tolerance                = 10000,
		turret                   = true,
		weaponVelocity           = 750,
		customparams             = {
			damagetype		     = "efighter",
			isupgraded           = isUpgraded,
		}, 
		damage                   = {
			default              = 100,
		},
	},  
}
