return {
	lootboxsilver = {
		acceleration = 0,
		activatewhenbuilt = true,
		autoheal = 1,
		brakerate = 1,
		buildcostenergy = 25000,
		buildcostmetal = 750,
		buildtime = 5000,
		canfight = false,
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		canselfdestruct = false,
		canstop = false,
		cantbetransported = false,
		capturable = true,
		category = "BUILDING",
		
		description = "Silver Lootbox: While you maintain control of it, this lootbox will provide extra resources.",
		energymake = 30,
		explodeas = "lootboxExplosion2",
		floater = true,
		footprintx = 4,
		footprintz = 4,
		icontype = "lootbox",
		idleautoheal = 10,
		idletime = 1800,
		levelground = false,
		mass = 4000,
		maxdamage = 4000,
		maxslope = 10,
		maxvelocity = 0.00000001,
		maxwaterdepth = 0,
		metalmake = 2,
		movementclass = "HOVERTANK2",
		movestate = 0,
		name = "Lootbox",
		noautofire = false,
		objectname = "lootboxes/lootbox4x4.s3o",
		pushResistant = true,
		script = "lootboxes/lootboxgold.cob",
		seismicsignature = 0,
		selfdestructas = "lootboxExplosion2",
		selfdestructcountdown = 9,
		sightdistance = 96,
		transportbyenemy = true,
		turninplace = false,
		turnrate = 0,
		unitname = "lootboxgold",
		upright = true,
		usebuildinggrounddecal = true,
		--waterline = 0,
		yardmap = "oooo oooo oooo oooo",
		customparams = {
			normaltex = "unittextures/bfaction_normals.dds",
			subfolder = "other/lootboxes",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:LootboxLightGold",
				[2] = "custom:LootboxBeaconSilver",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
	},
}
