return {
	lootboxplatinum = {
		acceleration = 0,
		activatewhenbuilt = true,
		autoheal = 1,
		brakerate = 1,
		buildcostenergy = 25000,
		buildcostmetal = 2500,
		buildtime = 5000,
		canfight = false,
		canguard = false,
		canmove = false,
		canpatrol = false,
		canrepeat = false,
		canselfdestruct = false,
		canstop = false,
		cantbetransported = false,
		capturable = true,
		category = "BUILDING",
		
		description = "Platinum Lootbox: While you maintain control of it, this lootbox will provide extra resources.",
		energymake = 80,
		explodeas = "lootboxExplosion4",
		floater = true,
		footprintx = 6,
		footprintz = 6,
		icontype = "lootbox",
		idleautoheal = 10,
		idletime = 1800,
		levelground = false,
		mass = 4000,
		maxdamage = 6000,
		maxslope = 10,
		maxvelocity = 0.00000001,
		maxwaterdepth = 0,
		metalmake = 4,
		movementclass = "HOVERTANK2",
		movestate = 0,
		name = "Lootbox",
		noautofire = false,
		objectname = "lootboxes/lootbox6x6.s3o",
		pushResistant = true,
		script = "lootboxes/lootboxgold.cob",
		seismicsignature = 0,
		selfdestructas = "lootboxExplosion4",
		selfdestructcountdown = 9,
		sightdistance = 96,
		transportbyenemy = true,
		turninplace = false,
		turnrate = 0,
		unitname = "lootboxgold",
		upright = true,
		usebuildinggrounddecal = true,
		--waterline = 0,
		yardmap = "oooooo oooooo oooooo oooooo oooooo oooooo",
		customparams = {
			normaltex = "unittextures/bfaction_normals.dds",
			subfolder = "other/lootboxes",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:LootboxLightGold",
				[2] = "custom:LootboxBeaconPlatinum",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
	},
}
