T0LandUnits = {
	"eallterrlight",
	"eamphibbuggy",
	"ehbotpeewee",
	"elighttank3",
	"zlightswarm",
	"xskulk",
	"xflea",
}

T1LandUnits = {
	"eallterrlight",
	"eamphibbuggy",
	"ehbotpeewee",
	"elighttank3",
	"zlightswarm",
	"eallterrriot",
	"eallterrriot_shotgun",
	"eallterrmed",
	"eamphibneedle",
	"eamphibriot",
	"eamphibriot_shotgun",
	"ehbotthud",
	"eriottank2",
	"eriottank2_shotgun",
	"eallterrassault",
	"eamphibarty",
	"eartytank",
	"eartytank_saturation",
	"zmedswarm",
	"zpyro",
	"xskulk",
	"xflea",
	"xcrasher",
	"xhammer",
	"xrocko",
	"xwarrior",
}

T2LandUnits = {
	"eallterrheavy",
	"eallterrshield",
	"eamphibmedtank",
	"eamphibrock",
	"ehbotrocko",
	"ehbotsniper",
	"eheavytank3",
	"emissiletank",
	"zskirmisher",
	"zassault",
	"xcrasher",
	"xhammer",
	"xrocko",
	"xwarrior",
}

T3LandUnits = {
	"eallterrheavy",
	"eallterrshield",
	"eamphibmedtank",
	"eamphibrock",
	"ehbotrocko",
	"ehbotsniper",
	"eheavytank3",
	"emissiletank",
	"zskirmisher",
	"zassault",
}

T4LandUnits = {
	"eallterranarchid",
	"eamphibleveler",
	"ehbotkarganneth",
	"elacerator",
	"zqueen",
	"eamphibbuggybig",
}
