local options= {

  {
    key    = 'StartingResources',
    name   = 'Starting Resources',
    desc   = 'Sets storage and amount of resources that players will start with',
    type   = 'section',
  },

  {
    key    = 'StartMetal',
    name   = 'Starting metal',
    desc   = 'Determines amount of metal and metal storage that each player will start with',
    type   = 'number',
    section= 'StartingResources',
    def    = 100,
    min    = 0,
    max    = 100,
    step   = 1,  -- quantization is aligned to the def value
                    -- (step <= 0) means that there is no quantization
  },
  {
   key    = 'StartMetal',
   scope  = 'team',
   name   = 'Team Starting metal',
   desc   = 'Determines amount of metal and metal storage this team will start with',
   type   = 'number',
   section= 'StartingResources',
   def    = 100,
   min    = 0,
   max    = 100,
   step   = 1,  -- quantization is aligned to the def value
   -- (step <= 0) means that there is no quantization
  },
  {
    key    = 'StartEnergy',
    name   = 'Starting energy',
    desc   = 'Determines amount of energy and energy storage that each player will start with',
    type   = 'number',
    section= 'StartingResources',
    def    = 250,
    min    = 0,
    max    = 250,
    step   = 1,  -- quantization is aligned to the def value
                    -- (step <= 0) means that there is no quantization
  },
  {
   key    = 'StartEnergy',
   scope  = 'team',
   name   = 'Team Starting energy',
   desc   = 'Determines amount of energy and energy storage that this team will start with',
   type   = 'number',
   section= 'StartingResources',
   def    = 250,
   min    = 0,
   max    = 250,
   step   = 1,  -- quantization is aligned to the def value
   -- (step <= 0) means that there is no quantization
  },

	{
    key='typemapsetting',
    name='Terrain Speed Boost',
    desc='Choose which map Speed Boost to use',
    type='list',
    section= 'mapsettings',
    def='alloff',
	    items = {
		{ key='mapdefault', name="Map Default", desc='Use map speed boost' },
		{ key='average', name="Average", desc='Each terrain types speed boost is averaged' },
		{ key='keepequal', name="Keep Equal", desc='Non-equal speedboost removed' },
		{ key='onlyimpassable', name="Only Impassable", desc='Override all speedboost except impassable terrain' },
		{ key='alloff', name="All Off", desc='Disable all speed boost' },
		},
	},
	{
		key="comm",
		name="Game Mode",
		desc="Choose the type of game",
		type="list",
		def="std",
		items = {
			{ key = "std", name = "Skirmish", desc = "Commander"  },
			{ key = "sandbox", name = "Sandbox", desc = "Testing!" },
			{ key = "feature", name = "Feature Placer", desc = "Not for gameplay, used for map development." }
			--{ key = "con", name = "Standard Constructor", desc = "A regular T1 construction unit" }
		},
	},  
		--
	--  chickens stuff
	--	
	{
       key="spawner",
       name="Spawner Ai Options",
       desc="Spawner Ai Options",
       type="section",
    },
	{
		key="mo_chickenstart",
		name="Burrow Placement",
		desc="Control where burrows spawn",
		type="list",
		def="avoid",
		section="spawner",
		items={
			{key="anywhere", name="Anywhere", desc="Burrows can spawn anywhere"},
			{key="avoid", name="Avoid Players", desc="Burrows do not spawn on player units"},
			{key="initialbox", name="Initial Start Box", desc="First wave spawns in chicken start box, following burrows avoid players"},
			{key="alwaysbox", name="Always Start Box", desc="Burrows always spawn in chicken start box"},
		}
	},
	-- {
		-- key="mo_queendifficulty",
		-- name="Queen Difficulty",
		-- desc="How hard doth the Chicken Queen",
		-- type="list",
		-- def="n_chickenq",
		-- section="spawner",
		-- items={
			-- {key="ve_chickenq", name="Very Easy", desc="Cakewalk"},
			-- {key="e_chickenq", name="Easy", desc="Somewhat Challenging"},
			-- {key="n_chickenq", name="Normal", desc="A Good Challenge"},
			-- {key="h_chickenq", name="Hard", desc="Serious Business"},
			-- {key="vh_chickenq", name="Very Hard", desc="Impossible"},
		-- }
	-- },
	{
		key    = "mo_queentime",
		name   = "Time until battleship comes",
		desc   = "A battle ship will come to attack after given time.",
		type   = "number",
		def    = 40,
		min    = 1,
		max    = 90,
		step   = 1,
		section= "spawner",
	},
	{
		key    = "mo_maxchicken",
		name   = "Unit limit",
		desc   = "Maximum number of units on map.",
		type   = "number",
		def    = 100,
		min    = 100,
		max    = 5000,
		step   = 50,
		section= "spawner",
	},
	{
		key    = "mo_graceperiod",
		name   = "Grace Period (Seconds)",
		desc   = "Time before spawner ai becomes active.",
		type   = "number",
		def    = 120,
		min    = 10,
		max    = 3600,
		step   = 10,
		section= "spawner",
	},
	-- {  --useless in gundam
		-- key    = "mo_queenanger",
		-- name   = "Add Queen Anger",
		-- desc   = "Killing burrows adds to queen anger.",
		-- type   = "bool",
		-- def    = true,
		-- section= "spawner",
    -- },
	-- dunno
	{
		key    = "mo_custom_burrowspawn",
		name   = "Elevator Spawn (Seconds)",
		desc   = "Time between elevator spawns.",
		type   = "number",
		def    = 120,
		min    = 1,
		max    = 600,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_chickenspawn",
		name   = "Wave Spawn Rate (Seconds)",
		desc   = "Time between chicken waves.",
		type   = "number",
		def    = 90,
		min    = 10,
		max    = 600,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_minchicken",
		name   = "Min Chickens Per Player",
		desc   = "Minimum Number of chickens before spawn chance kicks in",
		type   = "number",
		def    = 8,
		min    = 1,
		max    = 250,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_spawnchance",
		name   = "Spawn Chance (Percent)",
		desc   = "Percent chance of each chicken spawn once greater thwn the min chickens per player limit",
		type   = "number",
		def    = 33,
		min    = 0,
		max    = 100,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_angerbonus",
		name   = "Burrow Kill Anger (Seconds)",
		desc   = "Seconds added per burrow kill.",
		type   = "number",
		def    = 20,
		min    = 0,
		max    = 600,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_queenspawnmult",
		name   = "Queen Wave Size Mod",
		desc   = "Number of squads spawned by the queen at once.",
		type   = "number",
		def    = 1,
		min    = 0,
		max    = 5,
		step   = 1,
		section= "cust",
	},
	{
		key    = "mo_custom_expstep",
		name   = "Bonus Experience",
		desc   = "Exp each chicken will receive by the end of the game",
		type   = "number",
		def    = 1.5,
		min    = 0,
		max    = 2.5,
		step   = 0.1,
		section= "cust",
	},
	{
		key    = "mo_custom_lobberemp",
		name   = "Lobber EMP Duration",
		desc   = "Max duration of Lobber EMP artillery",
		type   = "number",
		def    = 4,
		min    = 0,
		max    = 30,
		step   = 0.5,
		section= "cust",
	},
}

return options
