unitDef                    = {
	acceleration                 = 1,
	brakeRate                    = 0.1,
	buildCostEnergy              = 0,
	buildCostMetal               = 59,
	builder                      = false,
	buildTime                    = 5,
	buildpic					 = "eamphibrock.png",
	canAttack                    = true,
	canGuard                     = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = "1",
	category                     = "LIGHT AMPHIB SUPPORT",
	description                  = [[Anti-Armor Missile Support Tank]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "mediumExplosionGeneric",
	footprintX                   = 2,
	footprintZ                   = 2,
	iconType                     = "mtd_lit_arm",
	idleAutoHeal                 = .5,
	idleTime                     = 2200,
	leaveTracks                  = false,
	maxDamage                    = 320,
	maxSlope                     = 28,
	maxVelocity                  = 4,
	maxReverseVelocity           = 1,
	maxWaterDepth                = 5000,
	metalStorage                 = 0,
	movementClass                = "TANK2",
	name                         = humanName,
	noChaseCategory              = "VTOL",
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = "mediumExplosionGeneric",
	side                         = "CORE",
	sightDistance                = 650,
	sonarDistance                = 650,
	stealth			             = true,
	seismicSignature             = 2,
	sonarStealth		         = false,
	smoothAnim                   = true,
	transportbyenemy             = false;
	--  turnInPlace              = false,
	--  turnInPlaceSpeedLimit    = 3.4,
	turnInPlace                  = true,
	turnRate                     = 5000,
	--  turnrate                 = 430,
	unitname                     = unitName,
	workerTime                   = 0,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"deathceg3", 
			"deathceg4", 
		}, 

		explosiongenerators      = {
			"custom:dirt",
			"custom:blacksmoke",
			"custom:jethtrail",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			def                  = "antiarmorrockets",
			badTargetCategory    = "BUILDING LIGHT WALL",
		},
		-- [2]                      = {
			-- def                  = "antiarmorrocketssalvo",
			-- badTargetCategory    = "BUILDING LIGHT WALL",
		-- },
	},
	customParams                 = {
		isupgraded			  	 = isUpgraded,
		unittype				 = "mobile",
		canbetransported 		 = "true",
		canareaattack            ="1",
		needed_cover             = 2,
		death_sounds             = "generic",
		RequireTech              = tech,
		armortype                = armortype,
		nofriendlyfire	         = "1",
		supply_cost              = supply,
		normaltex               = "unittextures/lego2skin_explorernormal.dds", 
		buckettex                = "unittextures/lego2skin_explorerbucket.dds",
		factionname	             = "ateran",
		corpse                   = "energycore",
	},
}

weaponDefs                 = {

	antiarmorrockets             = {
		AreaOfEffect             = 0,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		cegTag                   = "amphibrocktrail-optimized",
		explosionGenerator       = "custom:genericshellexplosion-medium-red",
		energypershot            = 0,
		fireStarter              = 70,
		tracks                   = true,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		model                    = "missilesmalllauncher.s3o",
		name                     = "Rockets",
		range                    = 700,
		reloadtime               = 1,
		weaponType		         = "MissileLauncher",
		smokeTrail               = false,
		soundStart               = "weapons/rocket1.wav",
		soundHit                 = "explosions/explode5.wav",
		startVelocity            = 250,
		tolerance                = 8000,
		turnrate                 = 5000,
		predictBoost	         = 0.5,
		turret                   = true,
		weaponAcceleration       = 50,
		flightTime               = 5,
		trajectoryHeight         = 1.5,
		weaponVelocity           = 1500,
		customparams             = {
			isupgraded		  	 = isUpgraded,
			damagetype		     = "antiarmoredair",  
		},     
		damage                   = {
			default              = 200,
		},
	},

	antiarmorrocketssalvo        = {
		AreaOfEffect             = 0,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		burst			         = 5,
		burstrate		         = 0.1,
		cegTag                   = "missiletrailsmall",
		explosionGenerator       = "custom:genericshellexplosion-medium-red",
		energypershot            = energycosttofire2,
		fireStarter              = 70,
		tracks                   = true,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		model                    = "missilesmalllauncher.s3o",
		name                     = "Rockets",
		range                    = 700,
		reloadtime               = 5,
		weaponType		         = "MissileLauncher",
		smokeTrail               = false,
		soundStart               = "weapons/rocket1.wav",
		soundHit                 = "explosions/explode5.wav",
		startVelocity            = 250,
		tolerance                = 8000,
		turnrate                 = 10000,
		predictBoost	         = 0.5,
		turret                   = true,
		weaponAcceleration       = 50,
		flightTime               = 5,
		trajectoryHeight         = 1.5,
		sprayangle		         = 10000,
		weaponVelocity           = 1500,
		customparams             = {
			isupgraded		  	 = isUpgraded,
			damagetype		     = "antiarmoredair",  
		},     
		damage                   = {
			default              = 200,
		},
	},
}
