unitDef                    = {
	acceleration                 = 1,
	airStrafe                    = false,
	airHoverFactor				 = 0,
	brakeRate                    = 1,
	buildCostEnergy              = 0,
	buildCostMetal               = 60,
	buildTime                    = 2.5,
	buildpic					 = "zaal_unitpics/zairbomber.png",
	canAttack                    = true,
	canFly                       = true,
	canGuard                     = true,
	canLoopbackAttack            = true,
	canMove                      = true,
	canPatrol                    = true,
	canstop                      = true,
	category                     = "LIGHT VTOL",
	collide                      = true,
	cruiseAlt                    = 140,
	description                  = [[Heavy Bomber]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "BUG_DEATH_MEDIUM",
	floater                      = true,
	footprintX                   = 7,
	footprintZ                   = 7,
	hoverAttack                  = false,
	iconType                     = "zbomber",
	idleAutoHeal                 = 2.5,
	idleTime                     = 5,
	maxacc						 = 1,
	maxDamage                    = 812,
	maxSlope                     = 90,
	maxVelocity                  = 12,
	maxWaterDepth                = 255,
	metalStorage                 = 0,
	moverate1                    = "8",
	name                         = humanName,
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = "BUG_DEATH_MEDIUM",
	side                         = "ARM",
	sightDistance                = 1000,
	smoothAnim                   = true,
	sonarDistance                = 0,
	transportbyenemy             = false;
	turnRate                     = 5000,
	turnradius					 = 250,
	unitname                     = unitName,
	upright						 = true,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"blood_spray", 
		}, 

		explosiongenerators      = {
			"custom:blood_spray",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"unitselect",
		},
	},
	weapons                      = {
		[1]                      = {
			onlytargetcategory = "BUILDING",
			def = "WEAPON",
		},
	},
	customParams                 = {
		unittype				 = "mobile",
		--    needed_cover       = 2,
		death_sounds             = "bug",
		RequireTech              = tech,
		armortype                = armortype,
		nofriendlyfire	         = "1",
		supply_cost              = supply,
		factionname	             = "zaal",
		corpse                   = "energycore",
		normaltex 				 = "unittextures/z_normals.dds",
		retreatRangeDAI			 = 0,
	},
}

weaponDefs                 = {
	weapon = {
		AreaOfEffect             = 150,
		avoidFriendly            = false,
		avoidFeature             = false,
		collideFriendly          = false,
		collideFeature           = false,
		burst			         = 12,
		burstrate		         = 0.2,
		--cegTag                   = "zaalspiketrail-optimized",
		explosionGenerator       = "custom:genericshellexplosion-medium-red",
		energypershot            = 0,
		fireStarter              = 70,
		tracks                   = false,
		impulseFactor            = 0,
		interceptedByShieldType  = 4,
		model					  = "ChickenDefenseModels/chickeneggyellow.s3o",
		name                     = "Spikes",
		range                    = 700,
		reloadtime               = 9,
		weaponType		         = "MissileLauncher",
		smokeTrail               = false,
		--soundStart               = "weapons/rocket1.wav",
		--soundHit                 = "explosions/explode5.wav",
		startVelocity            = 250,
		tolerance                = 8000,
		turnrate                 = 0,
		predictBoost	         = 0.5,
		turret                   = true,
		weaponAcceleration       = 50,
		flightTime               = 5,
		sprayangle		         = 3000,
		weaponVelocity           = 1000,
		customparams             = {
			damagetype		     = "default",
			nofriendlyfire	     = 1,
		},    
		damage = {
			default				  = 250,
		},
	},
}
