unitDef                     = {
	activatewhenbuilt             = true,
	buildAngle                    = 1024,
	buildCostEnergy               = 0,
	buildCostMetal                = 100,
	builder                       = true,
	buildTime                     = 5,
	buildpic					  = "zaal_unitpics/zhatch.png",
	canAttack			          = true,
	canBeAssisted                 = true,
	canGuard                      = true,
	canMove                       = true,
	canPatrol                     = true,
	canReclaim		              = false,
	canRepair		              = true,
	canstop                       = true,
	category                      = "BUILDING NOTAIR",
	description                   = [[Builds new Units - Upgrade to unlock new Tech levels]],
--	energyStorage                 = energyStorage,
--	energyUse                     = energyUse,
--	energyMake                    = energyMake,
	explodeAs                     = "BUG_DEATH_LARGE",
	footprintX                    = 24,
	footprintZ                    = 24,
	floater			              = true,
	iconType                      = "energy",
	idleAutoHeal                  = 5,
	idleTime                      = 300,
	maxDamage                     = 1,
	maxSlope                      = 90,
	maxWaterDepth                 = 99999999999,
--	metalStorage                  = metalStorage,
--	metalMake                     = metalMultiplier,
	name                          = humanName,
	objectName                    = objectName,
	script						  = script,
	radarDistance                 = 0,
	repairable		              = false,
	selfDestructAs                = "BUG_DEATH_LARGE",
	showNanoSpray                 = true,
	side                          = "CORE",
	sightDistance                = 250,
	smoothAnim                    = true,
	TEDClass                      = "PLANT",
	unitname                      = unitName,
	--  unitRestricted	          = 1,
	workerTime                    = 1,
	yardMap                       = [[yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy yyyyyyyyyyyyyyyyyyyyyyyy]],
	--usePieceCollisionVolumes      = true,
	--  modelCenterOffset	      = {108, 10, 0},
	sfxtypes                      = { 
		pieceExplosionGenerators  = { 
			"blood_spray",  
		}, 

		explosiongenerators       = {
			"custom:blood_spray",
		},
	},
	buildoptions                 = Shared.buildListZaal,
	sounds                        = {
		underattack               = "other/unitsunderattack1",
		select                    = {
			"BugSelect",
		},
	},
	weapons                       = {
	},
	customParams                  = {
		noalert					 = true,
		ProvideTech              = techprovided,
		unittype				  = "building",
		death_sounds              = "bug",
		armortype                 = "building", 
		normaltex 				 = "unittextures/zarm_normals.dds",
		factionname	              = "zaal",
		corpse                   = "energycore",
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "zgroundtexture.dds",
	BuildingGroundDecalSizeX      = 28,
	BuildingGroundDecalSizeY      = 28,
	BuildingGroundDecalDecaySpeed = 0.9,
}
