unitDef                    = {

	buildCostEnergy              = 0,
	buildCostMetal               = buildCostMetal,
	buildDistance                = buildDistance,
	builder                      = true,
	buildTime                    = 5,
	buildpic					 = "zaal_unitpics/ztenticle.png",
	blocking					 = true,
	CanAttack			         = false,
	CanAssist			         = true,
	canBeAssisted                = true,
	CanCapture                   = false,
	CanRepair			         = true,
	canRestore					 = false,
	cantBeTransported			 = true,
	canGuard                     = true,
	canHover                     = false,
	canMove                      = false,
	canPatrol                    = false,
	canreclaim		             = false,
	canstop                      = true,
	category                     = "BUILDING",
	description                  = [[Builds Units]],
	energyMake                   = 0,
	energyStorage                = 0,
	energyUse                    = 0,
	explodeAs                    = "BUG_DEATH_MEDIUM",
	floater			              = true,
	footprintX                   = 3,
	footprintZ                   = 3,
	iconType                     = "engineer",
	autoHeal					 = 10,
	idleAutoHeal                 = 25,
	idleTime                     = 5,
	levelground                  = true,
	maxDamage                    = 500,
	maxSlope                     = 90,
	maxVelocity                  = 0.001,
	maxReverseVelocity           = 0.001,
	maxWaterDepth                = 5000,
	metalmake                    = 0,
	metalStorage                 = 0,
	--movementClass                = "ZAALKBOT6",
	moveState			         = 2,
	name                         = humanName,
	noChaseCategory              = "VTOL LIGHT ARMORED BUILDING",
	objectName                   = objectName,
	script			             = script,
	radarDistance                = 0,
	repairable		             = false,
	selfDestructAs               = "BUG_DEATH_MEDIUM",
	showNanoSpray                = true,
	side                         = "ARM",
	sightDistance                = 500,
	smoothAnim                   = true,
	stealth			             = false,
	seismicSignature             = 2,
	unitname                     = unitName,
	upright                      = true,
	yardmap 					 = "ooo ooo ooo",
	workerTime                   = 1,
	TerraformSpeed               = 2147000,
	usePieceCollisionVolumes	 = true,
	sfxtypes                     = { 
		pieceExplosionGenerators = { 
			"blood_spray", 
		}, 

		explosiongenerators      = {
			"custom:blood_spray",
		},
	},
	sounds                       = {
		underattack              = "other/unitsunderattack1",
		ok                       = {
			"ack",
		},
		select                   = {
			"BugSelect",
		},
	},
	customParams                 = {
		unittype				 = "building",
		ProvideTech               = techprovided,
		canbetransported 		 = "false",
		needed_cover             = 1,
		death_sounds             = "bug",
		armortype                = armortype,
		normaltex               = "unittextures/zarm_normals.dds", 
		factionname	             = "zaal",  
	},
	useGroundDecal                = true,
	BuildingGroundDecalType       = "zgroundtexture.dds",
	BuildingGroundDecalSizeX      = 5,
	BuildingGroundDecalSizeY      = 5,
	BuildingGroundDecalDecaySpeed = 0.9,
}

--------------------------------------------------------------------------------

return lowerkeys({ [unitName]    = unitDef })

--------------------------------------------------------------------------------
